src/Entity/Payement.php
<?php

namespace App\Entity;

use App\Repository\PayementRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PayementRepository::class)
 */
class Payement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="datetime")
     */
    private $date_paiement;

    /**
     * @ORM\Column(type="boolean")
     */
    private $paiement_valide;

    /**
     * @ORM\ManyToOne(targetEntity=Reservation::class, inversedBy="payement", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $reservation;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDatePaiement(): ?\DateTimeInterface
    {
        return $this->date_paiement;
    }

    public function setDatePaiement(\DateTimeInterface $date_paiement): self
    {
        $this->date_paiement = $date_paiement;

        return $this;
    }

    public function __construct()
    {
        $this->date_paiement = new DateTime();
    }

    public function getPaiementValide(): ?bool
    {
        return $this->paiement_valide;
    }

    public function setPaiementValide(bool $paiement_valide): self
    {
        $this->paiement_valide = $paiement_valide;

        return $this;
    }

    public function getReservation(): ?Reservation
    {
        return $this->reservation;
    }

    public function setReservation(Reservation $reservation): self
    {
        $this->reservation = $reservation;

        return $this;
    }


}

src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 */
class Reservation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $TypeVoyage;

    /**
     * @ORM\Column(type="integer")
     */
    private $telephone;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombre_personnes;

    /**
     * @ORM\ManyToOne(targetEntity=Hotel::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $hotel;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToOne(targetEntity=Payement::class, mappedBy="reservation", cascade={"persist", "remove"})
     */
    private $payement;

 

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getTypeVoyage(): ?string
    {
        return $this->TypeVoyage;
    }

    public function setTypeVoyage(string $TypeVoyage): self
    {
        $this->TypeVoyage = $TypeVoyage;

        return $this;
    }

    public function getNombrePersonnes(): ?int
    {
        return $this->nombre_personnes;
    }

    public function setNombrePersonnes(int $nombre_personnes): self
    {
        $this->nombre_personnes = $nombre_personnes;

        return $this;
    }

    public function getHotel(): ?Hotel
    {
        return $this->hotel;
    }

    public function setHotel(?Hotel $hotel): self
    {
        $this->hotel = $hotel;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getPayement(): ?Payement
    {
        return $this->payement;
    }

    public function setPayement(Payement $payement): self
    {
        // set the owning side of the relation if necessary
        if ($payement->getReservation() !== $this) {
            $payement->setReservation($this);
        }

        $this->payement = $payement;

        return $this;
    }

    
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     */
    private $date_de_naissance;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isSubscribeToNewsletter = false;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="user", orphanRemoval=true)
     */
    private $reservations;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="user")
     */
    private $commentaires;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $date_de_naissance): self
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getIsSubscribeToNewsletter(): ?bool
    {
        return $this->isSubscribeToNewsletter;
    }

    public function setIsSubscribeToNewsletter(bool $isSubscribeToNewsletter): self
    {
        $this->isSubscribeToNewsletter = $isSubscribeToNewsletter;

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setUser($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getUser() === $this) {
                $reservation->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setUser($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getUser() === $this) {
                $commentaire->setUser(null);
            }
        }

        return $this;
    }

}

src/Controller/Membre/FactureController.php
<?php

namespace App\Controller\Membre;

use App\Entity\Hotel;
use App\Entity\Reservation;
use App\Repository\HotelRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Dompdf\Dompdf;
use Dompdf\Options;

class FactureController extends AbstractController
{
    /**
     * @Route("/facture/{id}", name="facture")
     */
    public function index(Reservation $reservation): Response
    {
  
    

        return $this->render('facture/index.html.twig', [
            'reservation' => $reservation,
        ]);
    }



    /**
     * @Route("/pdf/{id}", name="pdf")
     */
    public function PDF(Reservation $reservation)
        {
        // Configure Dompdf according to your needs
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');

        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);

        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('facture/pdf.html.twig', [
            'title' => "Voici votre facture.",
            'reservation' => $reservation 
        ]);

        // Load HTML to Dompdf
        $dompdf->loadHtml($html);

    

        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A3', 'paysage');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (inline view)
        $dompdf->stream("facture.pdf", [
            "Attachment" => false
        ]);
        die();
    }
    


}

src/Controller/Membre/MembreController.php
<?php

namespace App\Controller\Membre;

use App\Entity\Commentaire;
use App\Entity\User;
use App\Form\CommentaireType;
use App\Form\UserType;
use App\Repository\CommentaireRepository;
use App\Repository\ReservationRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Security\Core\User\UserInterface;

class MembreController extends AbstractController
{
    /**
     * @Route("/membre", name="membre")
     * @IsGranted("ROLE_MEMBER")
     */
    public function displayUser(UserInterface $user, UserRepository $userRepository): Response
    {

        return $this->render('membre/index.html.twig', [
            'controller_name' => 'MembreController',
        ]);
    }

    /**
     * @Route("/membre/coordonnees", name="coordonnees")
     * @IsGranted("ROLE_MEMBER")
     */
    public function displayUserAndModify(UserInterface $user, UserRepository $userRepository): Response
    {
        $member = $userRepository->find($user->getId());
        return $this->render('membre/membreCoordonnees.html.twig', [
            'controller_name' => 'MembreController',
            'user' => $member,
        ]);
    }

    /**
     * @Route("/membre/coordonnees/{id}", name="membre_modification")
     * @IsGranted("ROLE_MEMBER")
     */
    public function modifyUserInfos(User $user, Request $request) {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $user->getPassword();
            $user->getRoles();
            $user->isVerified();

            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();

            $this->addFlash('success', 'Votre compte a été modifié');
            return $this->redirectToRoute('coordonnees', ['id' => $user->getId()]);
        }

        return $this->render('membre/miniForm.html.twig', [
            'form' =>$form->createView(),
            'user' => $user,
        ]);
    }

    /**
     * @Route("/membre/delete/{id}", name="membre_supprimer")
     * @IsGranted("ROLE_MEMBER")
     */
    public function delete(User $user) {

        $session = new Session();
        $session->invalidate();

        $em = $this->getDoctrine()->getManager();
        $em->remove($user);
        $em->flush();

        return $this->redirectToRoute('app_login');
    }

    /**
     * @Route("/membre/listing-reservation", name="listing")
     * @IsGranted("ROLE_MEMBER")
     */
    public function listingReservation(ReservationRepository $reservationRepository) {

        $listing = $reservationRepository->findUserComments($this->getUser());
        // dd($listing);
        return $this->render('membre/reservationListing.html.twig', [
            'listing' => $listing,
        ]);
    }

    /**
     * @Route("/membre/listing-avis", name="listingAvis")
     * @IsGranted("ROLE_MEMBER")
     */
    public function listingAvis(CommentaireRepository $commentaireRepository) {

        $listing = $commentaireRepository->findUserComments($this->getUser());
        return $this->render('membre/avisListing.html.twig', [
            'listing' => $listing,
        ]);
    }
    
    /**
     * @Route("/membre/listing-avis/{id}", name="avis_modification")
     * @IsGranted("ROLE_MEMBER")
     */
    public function modifyUserReview(Commentaire $commentaire, Request $request) {
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($commentaire);
            $em->flush();

            $this->addFlash('success', 'Votre avis a été modifié');
            return $this->redirectToRoute('listingAvis');
        }

        return $this->render('membre/avisModifier.html.twig', [
            'form' =>$form->createView(),
            'commentaire' => $commentaire,
        ]);
    }



}

templates/membre/avisListing.html.twig
{% extends "membre/index.html.twig" %}

{% block title %}Espace membre / Mes avis{% endblock %}

{% block body %}
<h2 class="text-center">Mes avis</h2>


<div class="container">
<table class="table table-bordered border-dark align-middle">
  <thead>
    <tr>
      <th scope="col">Nom</th>
      <th scope="col">Prénom</th>
      <th scope="col">Formule</th>
      <th scope="col">Avis</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for item in listing %}
    <tr>
        <td>{{item.user.nom}}</td>
        <td>{{item.user.prenom}}</td>
        <td>{{item.hotel.nom}}</td>
        <td>{{item.message}}</td>
        <td><a class="btn btn-info" href=" {{path('avis_modification', {id:item.id})}} ">modifier</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<a class="btn btn-primary" href=" {{path('membre')}} " role="button"><--Retour</a>
</div>
{% endblock %}

templates/membre/avisModifier.html.twig
{% extends "base.html.twig" %}

{% block title %}Avis{% endblock %}

{% block body %}
    <div class="container">
        <h2 class="text-center">Avis</h2>

        {{form(form)}}
    </div>

{% endblock %}

templates/membre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Espace membre
{% endblock %}

{% block body %}
<div class="container">
	<h1>Espace membre</h1>
	<p>Bienvenue dans l'espace membre</p>
    <ul>
        <li>
            <a href ="{{path('coordonnees')}}">Vos coordonnées</a>
        </li>
        <li>
            <a href ="{{path('listing')}}">Vos réservations</a>
        </li>
        <li>
            <a href =" {{path('listingAvis')}} ">Vos avis</a>
        </li>
    </ul>
</div>


{% endblock %}

templates/membre/membreCoordonnees.html.twig
{% extends "membre/index.html.twig" %}

{% block title %}Espace membre / Coordonnées{% endblock %}

{% block body %}
<div class="container">
    <h1>Espace membre</h1>
    <h2>Vos coordonnées</h2>
    <div class="coordonnees">
        <p><strong>Nom</strong> : {{ user.nom }}</p>
        <p><strong>Prénom</strong> : {{ user.prenom }}</p>
        <p><strong>Email</strong> : {{ user.email }}</p>
        <p><strong>Date de naissance</strong> : {{ user.dateDeNaissance|date('d-m-Y') }}</p>
    </div>
    <div class="btnBackOrModify">
        <a class="btn btn-secondary" href="{{path('membre')}}"><- Retour</a>
        <a type="button" class="btn btn-info" href="{{path('membre_modification', {id: user.id})}}">Modifier</a>
        <a class="btn btn-danger" href="{{path('membre_supprimer', {id:user.id})}}" onclick="return confirm('Voulez-vous vraiment supprimer votre compte ?');">Supprimer son compte</a>
    </div>
</div>


{% endblock %}

templates/membre/miniForm.html.twig
{% extends "membre/index.html.twig" %}

{% block title %}Espace membre / Modification{% endblock %}

{% block body %}
<div class="container">
    <h2>Modification du compte</h2>
    <a class="btn btn-primary" href="{{path('coordonnees')}}"><- Retour</a>
{{ form_start(form) }}

    <div class="row mt-3">
        <div class="col-md-6">
    {{ form_row(form.nom) }}
        </div>
        <div class="col-md-6">
    {{ form_row(form.prenom) }}
        </div>
    </div>  
    <div class="row mt-3">  
    {{ form_row(form.date_de_naissance) }}
    </div>
    <div class="row mt-3"> 
    {{ form_row(form.email) }}
    </div>
    <div class="row mt-3"> 
    {{ form_row(form.isSubscribeToNewsletter) }}
    </div>
    <div class="row mt-3"> 
    {{ form_row(form.submit) }} 

    </div>


{{ form_end(form) }}

</div>

{% endblock %}

templates/membre/reservationListing.html.twig
{% extends "membre/index.html.twig" %}

{% block title %}Espace membre / Mes réservations{% endblock %}

{% block body %}

<div class="container">
<h2 class="text-center">Mes réservations</h2>
<table class="table table-bordered border-dark">
  <thead>
    <tr>
      <th scope="col">Formule</th>
      <th scope="col">Date de la réservation</th>
      <th scope="col">Prix</th>
      <th scope="col">Facture</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
        {% for lis in listing %}
    <tr>
      <td> {{lis.hotel.nom}} </td>
      <td>{{lis.payement.datePaiement |date('d/m/Y')}}</td>
      <td>
          {{ (lis.hotel.prix * lis.nombrePersonnes) |price}}
      </td>
      <td>
        <a href=" {{path('pdf', {id:lis.id})}} ">Version pdf</a>
      </td>
      <td>
        <ul>
          <li>
            <a href=" {{path('hotel_details', {id:lis.hotel.id})}} ">Voir plus de détails</a>
          </li>
          <li>
            <a href=" {{path('hotel_avis', {id:lis.hotel.id})}} ">Ajouter un avis </a>
          </li>
          <li>
            <a href="#">Annuler la réservation</a>
          </li>
        </ul>
      </td>
    </tr>
          {% endfor %}
  </tbody>
</table>
<a class="btn btn-primary" href=" {{path('membre')}} " role="button"><--Retour</a>
</div>
{% endblock %}