src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 */
class Reservation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $TypeVoyage;

    /**
     * @ORM\Column(type="integer")
     */
    private $telephone;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombre_personnes;

    /**
     * @ORM\ManyToOne(targetEntity=Hotel::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $hotel;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToOne(targetEntity=Payement::class, mappedBy="reservation", cascade={"persist", "remove"})
     */
    private $payement;

 

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getTypeVoyage(): ?string
    {
        return $this->TypeVoyage;
    }

    public function setTypeVoyage(string $TypeVoyage): self
    {
        $this->TypeVoyage = $TypeVoyage;

        return $this;
    }

    public function getNombrePersonnes(): ?int
    {
        return $this->nombre_personnes;
    }

    public function setNombrePersonnes(int $nombre_personnes): self
    {
        $this->nombre_personnes = $nombre_personnes;

        return $this;
    }

    public function getHotel(): ?Hotel
    {
        return $this->hotel;
    }

    public function setHotel(?Hotel $hotel): self
    {
        $this->hotel = $hotel;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getPayement(): ?Payement
    {
        return $this->payement;
    }

    public function setPayement(Payement $payement): self
    {
        // set the owning side of the relation if necessary
        if ($payement->getReservation() !== $this) {
            $payement->setReservation($this);
        }

        $this->payement = $payement;

        return $this;
    }

    
}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('adresse', TextType::class, ['label' => "Adresse", ])
            ->add('telephone', NumberType::class, ['label' => "Telephone", ])
            ->add('nombre_personnes', NumberType::class, [
                'label' => "Nombre de personnes", 
                ])
            ->add('TypeVoyage', TextType::class, ['label' => "Type de voyage", ])
            ->add('submit', SubmitType::class, ['label' => "Envoyer",])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/Membre/ReservationController.php
<?php

namespace App\Controller\Membre;

use App\Entity\Hotel;
use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Repository\HotelRepository;
use App\Repository\ReservationRepository;
use App\Repository\VolRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ReservationController extends AbstractController
{
    /**
     * @Route("/reservation/{id}", name="reservation")
     */
    public function reservation(Hotel $hotel, Request $request,ReservationRepository $reservationRepository)
    {

        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        $getReservation = $hotel->getReservations();
        $getValues = $getReservation->getValues();
        $listing = $reservationRepository->findUserReservation($this->getUser());
        $user = $this->getUser();
   
        if ($form->isSubmitted() && $form->isValid()) {
            $reservation              
                ->setHotel($hotel)
                ->setUser($this->getUser());

            $getHotel = $reservation->getHotel(); 
            $getVols = $getHotel->getVols();
            $getValues = $getVols->getValues();
            $vol = $getValues[0];
            
            if($vol->getVoyageAffaire()){

                if( $vol->getClasseAffaire() < $reservation->getNombrePersonnes()){
                    $this -> addFlash('danger',"Le nombre de place reservé est superieur au nombre de place disponible.");
                    return $this->redirectToRoute('reservation', [ 'id' => $hotel->getId() ]);
                }
            
            }else{

                if( $vol->getClasseEconomique() < $reservation->getNombrePersonnes()){
                    $this -> addFlash('danger',"Le nombre de place reservé est superieur au nombre de place disponible.");
                    return $this->redirectToRoute('reservation', [ 'id' => $hotel->getId() ]);
                }

            }     
            $em = $this->getDoctrine()->getManager();
            $em->persist($reservation);
            $em->flush();

            $this->addFlash('success', "la reservation a été enregistrée ");
            return $this->redirectToRoute('reservation', [ 'id' => $hotel->getId() ]);
        }
        
        return $this->render('reservation/reservation_formule.html.twig', [
            'form'=> $form->createView(),
            'hotel' => $hotel,
            'listing' => $listing,
            'values' => $getValues,
            'user' => $user,
            'reservation' => $reservation,
        ]);
    }

     /**
     * @Route("/reservation/modification/{id}", name="reservation_modification")
     */
    public function update_reservation(Reservation $reservation,Request $request): Response
    {    
        return $this->handleForm($reservation , $request); 
    }
 
    public function handleForm(Reservation $reservation, Request $request)
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $hotel = $reservation->getHotel();
            
            $getVols = $hotel->getVols();
            $getValues = $getVols->getValues();
            $vol = $getValues[0];
              
            if($vol->getVoyageAffaire()){

                if( $vol->getClasseAffaire() < $reservation->getNombrePersonnes()){
                    $this -> addFlash('danger',"Le nombre de place reservé est superieur au nombre de place disponible.");
                    return $this->redirectToRoute('reservation_modification', [ 'id' => $reservation->getId() ]);
                }
            
            }else{
                if( $vol->getClasseEconomique() < $reservation->getNombrePersonnes()){
                    $this -> addFlash('danger',"Le nombre de place reservé est superieur au nombre de place disponible.");
                    return $this->redirectToRoute('reservation_modification', [ 'id' => $reservation->getId() ]);
                }

            }  

         $em = $this->getDoctrine()->getManager();
         $em->persist($reservation);
         $em->flush();
            
            $this->addFlash('success', "votre reservation est modifié");
            return $this->redirectToRoute('reservation', [ 'id' => $hotel->getId() ]);
            }
            
            return $this->render('reservation/form_mofidication.html.twig', [
                'reservation' => $reservation,
                'form' => $form->createView(),
            ]);
        }

}

templates/reservation/_affichage_reservation.html.twig
    <div class="row text-center  reservation_resultat">
        <b>nom :</b> {{v.user.nom}} 
        <br>
        <b>prenom :</b> {{v.user.prenom}} 
        <br>
        <b>adresse :</b> {{v.adresse}}
        <br>
        <b>telephone :</b>0{{v.telephone}}
        <br> 
        <b>nombre de personnes :</b> {{v.nombrePersonnes}}
        <br>
        <b>type de voyage :</b> {{v.typeVoyage}}
        <br>
    </div>

templates/reservation/_form_reservation.html.twig
<div class="container"> 
       {{ form_start(form) }}
       <div class="text-center reservation_formulaire">     
       {{ form_row(form.adresse)}}
       {{ form_row(form.telephone)}}
       {{ form_row(form.nombre_personnes)}}
       {{ form_row(form.TypeVoyage)}}
       {{ form_row(form.submit)}}
       </div>
       {{ form_end(form) }}  
</div>

templates/reservation/form_mofidication.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
<div class="container"> 
       {{ form_start(form) }}
       <div class="text-center reservation_formulaire">     
       {{ form_row(form.adresse)}}
       {{ form_row(form.telephone)}}
       {{ form_row(form.nombre_personnes)}}
       {{ form_row(form.TypeVoyage)}}
       {{ form_row(form.submit)}}
       </div>
       {{ form_end(form) }}  
</div>
{% endblock %}

templates/reservation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
<div class="container">
  {{ form_start(form) }}
    <div class="text-center">
      <div class="col-sm-6">{{ form_row(form.adresse)}}</div>
      <div class="col-sm-6">{{ form_row(form.telephone)}}</div>
      <div class="col-sm-6">{{ form_row(form.NombreEnfant)}}</div>
      <div class="col-sm-6">{{ form_row(form.TypeVoyage)}}</div>
      <div class="col-sm-6">{{ form_row(form.submit)}}</div>
    </div>
  

  {{ form_end(form) }}
</div>
{% endblock %}

templates/reservation/reservation_formule.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}

<div class="container_admin_liste_hotel">
      {% include "admin/crud_voyage/hotel/_affichage_hotel.html.twig" %}
          </ul>                            
      </div>
  </div>
</div>
<div class="container_admin_liste_vol">
        {% for vol in hotel.vols %}             
            <div class="admin_liste_vol">
                <div class="admin_DepartVol_liste_vol mt-3">
                    {% include "admin/crud_voyage/hotel/_affichage_vol.html.twig" %} 
                </div> 
        {% endfor %}
    </div>
 </div>
 
{% if listing is not empty %}
    {% if values is empty %}
        <div class="lead text-center mt-5 reservation_formulaire "><h3>Reservé votre Formule de voyage</h3> </div>
        {% include "reservation/_form_reservation.html.twig" %} 
    {% else %}
        {% for v in values %}
            {% if v.user.id == user.id %}      
                {% if v.hotel.id == hotel.id  %}
                        {% if listing[0].user.id == user.id %}
                            <div class="lead text-center mt-5 reservation_resultat"><h3>Votre Formule de voyage</h3> </div>
                            {% include "reservation/_affichage_reservation.html.twig" %}
                                {% if listing[0].payement is null %}
                                    <div class="text-center mt-5"> 
                                        <a href="{{path('reservation_modification',{id:listing[0].id})}}" class="btn btn-info mb-5">Modifier</a>
                                        <a href="{{path('payement',{id:listing[0].id})}}" class="btn btn-primary mb-5">Paiement</a>
                                    </div> 
                                    {% else %}
                                    <div class"mt-5"><hr></div>
                                {% endif %}
                        {% endif %} 
                {% endif %} 
            {% else %}
                {% if values is empty %}
                    <div class="lead text-center mt-5 reservation_formulaire "><h3>Reservé votre Formule de voyage</h3> </div>
                    {% include "reservation/_form_reservation.html.twig" %}
                {% endif %}
            {% endif %}  
        {% endfor %}
    {% endif %} 
{% else %}
    <div class="lead text-center mt-5 reservation_formulaire "><h3>Reservé votre Formule de voyage</h3> </div>
    {% include "reservation/_form_reservation.html.twig" %} 
{% endif %}

{% endblock %}