src/Entity/Hotel.php
<?php

namespace App\Entity;

use App\Repository\HotelRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=HotelRepository::class)
 */
class Hotel
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Merci d'indiquer le nom de l'hôtel")
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Merci d'indiquer l'adresse de l'hôtel")
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Merci d'indiquer un prix de l'hôtel")
     */
    private $prix;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=50, minMessage="Merci d'écrire au moins {{ limit }} caractères")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image3;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image4;

    /**
     * @ORM\OneToMany(targetEntity=Vol::class, mappedBy="hotel", orphanRemoval=true)
     */
    private $vols;

    /**
     * @ORM\Column(type="boolean")
     */
    private $promotion=false;

    /**
     * @ORM\Column(type="integer")
     */
    private $promotion_prix = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private $etoile;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="hotel", orphanRemoval=true)
     */
    private $reservations;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="hotel")
     */
    private $commentaires;


    public function __construct()
    {
        $this->vols = new ArrayCollection();
        $this->reservations = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
    public function getImagePath(): string
    {
        return 'images/images_hotels/' . $this->image;
    }
    public function getImageDirectory(): string
    {
        return 'hotel';
    }

    public function getImage2(): ?string
    {
        return $this->image2;
    }

    public function setImage2(?string $image2): self
    {
        $this->image2 = $image2;

        return $this;
    }

    public function getImage3(): ?string
    {
        return $this->image3;
    }

    public function setImage3(?string $image3): self
    {
        $this->image3 = $image3;

        return $this;
    }

    public function getImage4(): ?string
    {
        return $this->image4;
    }

    public function setImage4(?string $image4): self
    {
        $this->image4 = $image4;

        return $this;
    }

    /**
     * @return Collection|Vol[]
     */
    public function getVols(): Collection
    {
        return $this->vols;
    }

    public function addVol(Vol $vol): self
    {
        if (!$this->vols->contains($vol)) {
            $this->vols[] = $vol;
            $vol->setHotel($this);
        }

        return $this;
    }

    public function removeVol(Vol $vol): self
    {
        if ($this->vols->removeElement($vol)) {
            // set the owning side to null (unless already changed)
            if ($vol->getHotel() === $this) {
                $vol->setHotel(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return $this->nom;
    }

    public function getPromotion(): ?bool
    {
        return $this->promotion;
    }

    public function setPromotion(bool $promotion): self
    {
        $this->promotion = $promotion;

        return $this;
    }

    public function getPromotionPrix(): ?int
    {
        return $this->promotion_prix;
    }

    public function setPromotionPrix(int $promotion_prix): self
    {
        $this->promotion_prix = $promotion_prix;

        return $this;
    }

    public function getEtoile(): ?int
    {
        return $this->etoile;
    }

    public function setEtoile(int $etoile): self
    {
        $this->etoile = $etoile;

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setHotel($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getHotel() === $this) {
                $reservation->setHotel(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setHotel($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getHotel() === $this) {
                $commentaire->setHotel(null);
            }
        }

        return $this;
    }


}

src/Entity/Vol.php
<?php

namespace App\Entity;

use App\Repository\VolRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=VolRepository::class)
 */
class Vol
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     *  @Assert\NotBlank(message="Merci d'indiquer une date")
     */
    private $date_de_depart;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank(message="Merci d'indiquer une date")
     */
    private $date_arrive;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Merci d'indiquer un nom")
     */
    private $nom_aeroport_depart;

    /**
     * @ORM\Column(type="string", length=255)
     *  @Assert\NotBlank(message="Merci d'indiquer un nom")
     */
    private $nom_aeroport_arrive;

    /**
     * @ORM\Column(type="string", length=255)
     *  @Assert\NotBlank(message="Merci d'indiquer un nom")
     */
    private $nom_ville_arrive;
    /**
     * @ORM\Column(type="time")
     */
    private $duree_vol;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $compagnie_depart;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $compagnie_retour;

    /**
     * @ORM\Column(type="datetime")
     */
    private $retour_date_de_depart;

    /**
     * @ORM\Column(type="datetime")
     */
    private $retour_date_arrive;

    /**
     * @ORM\ManyToOne(targetEntity=Hotel::class, inversedBy="vols")
     * @ORM\JoinColumn(nullable=false)
     */
    private $hotel;

    /**
     * @ORM\Column(type="boolean")
     */
    private $voyage_affaire = false;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut_sejour;

    /**
     * @ORM\Column(type="date")
     */
    private $date_fin_sejour;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pays;

    /**
     * @ORM\Column(type="integer")
     */
    private $classe_affaire;

    /**
     * @ORM\Column(type="integer")
     */
    private $classe_economique;

 
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDeDepart(): ?\DateTimeInterface
    {
        return $this->date_de_depart;
    }

    public function setDateDeDepart(\DateTimeInterface $date_de_depart): self
    {
        $this->date_de_depart = $date_de_depart;

        return $this;
    }

    public function getDateArrive(): ?\DateTimeInterface
    {
        return $this->date_arrive;
    }

    public function setDateArrive(\DateTimeInterface $date_arrive): self
    {
        $this->date_arrive = $date_arrive;

        return $this;
    }

    public function getNomAeroportDepart(): ?string
    {
        return $this->nom_aeroport_depart;
    }

    public function setNomAeroportDepart(string $nom_aeroport_depart): self
    {
        $this->nom_aeroport_depart = $nom_aeroport_depart;

        return $this;
    }

    public function getNomAeroportArrive(): ?string
    {
        return $this->nom_aeroport_arrive;
    }

    public function setNomAeroportArrive(string $nom_aeroport_arrive): self
    {
        $this->nom_aeroport_arrive = $nom_aeroport_arrive;

        return $this;
    }

    public function getNomVilleArrive(): ?string
    {
        return $this->nom_ville_arrive;
    }

    public function setNomVilleArrive(string $nom_ville_arrive): self
    {
        $this->nom_ville_arrive = $nom_ville_arrive;

        return $this;
    }
    public function getDureeVol(): ?\DateTimeInterface
    {
        return $this->duree_vol;
    }

    public function setDureeVol(\DateTimeInterface $duree_vol): self
    {
        $this->duree_vol = $duree_vol;

        return $this;
    }

    public function getCompagnieDepart(): ?string
    {
        return $this->compagnie_depart;
    }

    public function setCompagnieDepart(string $compagnie_depart): self
    {
        $this->compagnie_depart = $compagnie_depart;

        return $this;
    }

    public function getCompagnieRetour(): ?string
    {
        return $this->compagnie_retour;
    }

    public function setCompagnieRetour(string $compagnie_retour): self
    {
        $this->compagnie_retour = $compagnie_retour;

        return $this;
    }

    public function getRetourDateDeDepart(): ?\DateTimeInterface
    {
        return $this->retour_date_de_depart;
    }

    public function setRetourDateDeDepart(\DateTimeInterface $retour_date_de_depart): self
    {
        $this->retour_date_de_depart = $retour_date_de_depart;

        return $this;
    }

    public function getRetourDateArrive(): ?\DateTimeInterface
    {
        return $this->retour_date_arrive;
    }

    public function setRetourDateArrive(\DateTimeInterface $retour_date_arrive): self
    {
        $this->retour_date_arrive = $retour_date_arrive;

        return $this;
    }

    public function getHotel(): ?Hotel
    {
        return $this->hotel;
    }

    public function setHotel(?Hotel $hotel): self
    {
        $this->hotel = $hotel;

        return $this;
    }

    public function getVoyageAffaire(): ?bool
    {
        return $this->voyage_affaire;
    }

    public function setVoyageAffaire(bool $voyage_affaire): self
    {
        $this->voyage_affaire = $voyage_affaire;

        return $this;
    }
    

    public function getDateDebutSejour(): ?\DateTimeInterface
    {
        return $this->date_debut_sejour;
    }

    public function setDateDebutSejour(\DateTimeInterface $date_debut_sejour): self
    {
        $this->date_debut_sejour = $date_debut_sejour;

        return $this;
    }

    public function getDateFinSejour(): ?\DateTimeInterface
    {
        return $this->date_fin_sejour;
    }

    public function setDateFinSejour(\DateTimeInterface $date_fin_sejour): self
    {
        $this->date_fin_sejour = $date_fin_sejour;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }
    
    public function __toString()
    {
        return $this->pays;
    }

    public function getClasseAffaire(): ?int
    {
        return $this->classe_affaire;
    }

    public function setClasseAffaire(int $classe_affaire): self
    {
        $this->classe_affaire = $classe_affaire;

        return $this;
    }

    public function getClasseEconomique(): ?int
    {
        return $this->classe_economique;
    }

    public function setClasseEconomique(int $classe_economique): self
    {
        $this->classe_economique = $classe_economique;

        return $this;
    }


   




}

src/Controller/HotelrequestController.php
<?php

namespace App\Controller;

use App\Entity\Commentaire;
use App\Entity\Hotel;
use App\Entity\SearchData;
use App\Form\CommentaireType;
use App\Form\SearchFormType;
use App\Repository\CommentaireRepository;
use App\Repository\HotelRepository;
use DateTime;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HotelrequestController extends AbstractController
{
    /**
     * @Route("/request", name="hotelrequest")
     */
    public function Search(HotelRepository $hotelRepository, Request $request,PaginatorInterface $paginator): Response
    {
        $data = new SearchData();
       
        $form = $this->createForm(SearchFormType::class, $data);
        $form->handleRequest($request);
        
        $hotels = $paginator->paginate(
            $hotelRepository->findSearch($data),
                   $request->query->getInt('page', 1),
                   6 );
                   
        return $this->render('hotelrequest/liste_hotel_requete.html.twig', [
            'hotels' => $hotels,
            'form'=>$form->createView()
        ]);
    }

    /**
     * @Route("/request_hotel/details/{id}", name="hotel_details")
     */
    public function hotelDetails(Hotel $hotel): Response
    {
        return $this->render('hotelrequest/hotel_requete_details.html.twig', [
            'hotel' => $hotel,
        ]);
    }

    /**
     * @Route("/request_hotel/details/avis/{id}", name="hotel_avis")
     */
    public function avisHotel(Hotel $hotel, Request $request): Response
    {
        $commentaire = new Commentaire();
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $commentaire->setHotel($hotel);
            $commentaire->setUser($this->getUser());
            $commentaire->setCreatedAt(new DateTime());

            $em= $this->getDoctrine()->getManager();
            $em->persist($commentaire);
            $em->flush();

            $this->addFlash('success', 'Merci pour votre commentaire');
            return $this->redirectToRoute('hotel_details', ['id' => $hotel->getId()]);
        }

        return $this->render('hotelrequest/avis_hotel.html.twig', [
            'hotel' => $hotel,
            'form' =>$form->createView(),
        ]);
    }



}

templates/hotelrequest/_affichage_hotel_detail.html.twig
<div class="container_hotel_details">
    <div class="hotel_details_top mb-3">
        <div class="hotel_details_titre">
            <ul>
                <li class="hotel_details_titre_etoile">
                    <h4><b>{{hotel.nom}}</b></h4>
                    <div id="list">
                        <img id="item" src="{{ asset('images/image_vol/etoile.png') }}" width="25px" height="25px">
                    </div>
                </li>
                <li><a href=""><i class="fas fa-map-marker-alt"></i> {{ hotel.adresse }}</a></li>
            </ul>
        </div>
        <div class="hotel_details_share_reseaux">
            <!-- Load Facebook SDK for JavaScript -->
                <div id="fb-root"></div>
                <script async defer crossorigin="anonymous" src="https://connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v10.0" nonce="Jkro3s8l"></script>
                {# // <script>(function(d, s, id) {
                // var js, fjs = d.getElementsByTagName(s)[0];
                // if (d.getElementById(id)) return;
                // js = d.createElement(s); js.id = id;
                // js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
                // fjs.parentNode.insertBefore(js, fjs);
                // }(document, 'script', 'facebook-jssdk'));</script> #}
                <!-- Your share button code -->
                <div class="fb-share-button" data-href="http://127.0.0.1:8000/request_hotel/details/{{hotel.id}}" data-layout="button" data-size="large"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Partager</a></div>
        </div>
    </div>

    <div class="hotel_details_images">
        <div class="hotel_details_imgG">
            <img src="{{ asset('images/hotel/' ~ hotel.image) }}" class="card-img-top" alt="...">
        </div>
        <div class="hotel_details_imgD">
            <div class="hotel_details_imgD_top">
                <img src="{{ asset('images/hotel/' ~ hotel.image2) }}" class="card-img-top" alt="...">
                <img src="{{ asset('images/hotel/' ~ hotel.image3) }}" class="card-img-top" alt="...">
            </div>
            <div class="hotel_details_imgD_bottom">
                <img src="{{ asset('images/hotel/' ~ hotel.image4) }}" class="card-img-top" alt="...">
                {# style="width: 150px; height: 50px;" #}
                <img src="{{ asset('images/image_vol/voirplus.png') }}" alt="" >
            </div>
        </div>
    </div>
    <div class="hotel_details_infoPrix mt-4">
        <div class="hotel_details_info">
            <ul>
                <li><a href="">Information général</a></li>
                <li><a href="">Vol</a></li>
                <li><a href="">Avis</a></li>
            </ul>
        </div>
        <div class="hotel_details_prix">
            <ul>
                <li>
                Dès {% if hotel.promotion %}
                        <b style="color: green; font-size:2.2rem;"> {{ hotel.prix |price}}</b> au lieu de
                        <em style="color: red;"><strike> {{ hotel.promotionPrix |price}}</strike></em> <br>
                    {% else %}
                        <h4><b style="color: red; font-size:2rem;"> {{ hotel.prix |price}}</b></h4><br>   
                    {% endif %} <em>Prix par personne, 7nuits</em> 
                </li>
            </ul>
        </div>
    </div>
    <div class="hotel_details_description mt-5">
        <h5>Information général</h5>
        <p class="card-title">{{ hotel.description }}</p> 
    </div>
</div>

templates/hotelrequest/_form_filter.html.twig
{# {{form_start(form,{attri: {class: 'filter'}}) }} #}
{{form_start(form) }}
{{form_row(form.q)}}
<h4>Pays</h4>
{{form_row(form.pays)}}
{{form_row(form.depart)}}
{{form_row(form.retour)}}   
<h4>Prix</h4>
<div class="row ">
    <div class="col-md-6">
        {{form_row(form.min)}}
    </div>
    <div class="col-md-6">
        {{form_row(form.max)}}
    </div>
</div>
<h4>classe affaire</h4>
{{form_row(form.economie)}}
{{form_row(form.affaire)}}
<h4>classe affaire</h4>
{{form_row(form.promotion)}}
{{form_end(form)}}

templates/hotelrequest/avis_hotel.html.twig
{% extends "base.html.twig" %}

{% block title %}Avis{% endblock %}

{% block body %}
    <div class="container">
        <h2 class="text-center">Avis</h2>

        {{form(form)}}
    </div>

{% endblock %}

templates/hotelrequest/hotel_requete_details.html.twig
{% extends "base.html.twig" %}

{% block title %}hotels details{% endblock %}

{% block javascripts %}
    {{ parent() }}
<script type="text/javascript">
  function cloneItem() {
      var item = document.getElementById("item");
      var list = document.getElementById("list");
      var clonedItem = item.cloneNode(true) ;
      list.appendChild(clonedItem);
  }

  for(var i = 1; i < {{hotel.etoile}}; i++) {
    cloneItem();

  }
</script>
{% endblock %}

{% block body %}
<div class="text-start mt-5 mb-3">
    <a href="{{path("hotelrequest")}}" class="btn btn-primary">Retour liste des hotels</a>
</div>
    {% include "hotelrequest/_affichage_hotel_detail.html.twig" %}  
<div class="hotel_details_classe_vol text-center mt-5">
        <div class="hotel_detail_trait"></div>
        <h3><b>VOL INCLUS</b></h3>
        <p class="card-title">
            <b>Vol  
                {% for d in hotel.vols %}
                    {% if d.voyageAffaire %}
                            classe affaire 
                    {% else %}
                            classe économique
                    {% endif %}
                {% endfor %}
            </b>
        </p> 
        <div class="hotel_detail_trait"></div>
</div>



<div class="container_admin_liste_vol"> 
    {% for vol in hotel.vols %}             
        <div class="admin_liste_vol">
            <div class="admin_DepartVol_liste_vol mt-3">
                {% include "admin/crud_voyage/hotel/_affichage_vol.html.twig" %} 
{# LES AVIS #}
                <hr />
                <div class="container">
                    <div style="display:flex; align-items: center;">
                        <h3>Avis ({{hotel.commentaires.count}}) </h3>
                        
                    </div>
                    <div>
                        {% for hotel in hotel.commentaires %}
                        <h1>{{hotel.note|star}} {{hotel.note}}/5</h1>
                        <div class="my-3">
                            <b>Publié le {{hotel.createdAt| date('d-m-Y')}} Par {{hotel.user.prenom}} {{hotel.user.nom}}</b>
                        </div>
                        <div>

                            {{hotel.message|nl2br}}
                        </div>
                        <hr>
                        {% endfor %}
                    </div>
                </div>    
                <hr/>

{# BOUTON RESERVER SI CONNECTER  #}
         <div class="text-center"> 
            {% if is_granted('ROLE_MEMBER') %}
                <a href=" {{path('reservation',{id:hotel.id}) }} " class="btn btn-primary mb-5">Reserver votre voyage</a>
            {% else %}
                <a href="{{ path('app_login') }}" class="btn btn-primary mb-5">Connectez-vous avant de réserver</a>
            {% endif %}   
            
        </div> 
    {% endfor %}
</div>
{% endblock %}

templates/hotelrequest/liste_hotel_requete.html.twig
{% extends "base.html.twig" %}

{% block title %}Recherche des hotels {% endblock %}
 {% block javascripts %}
    <script>
    $(document).ready(function() {
        // you may need to change this code if you are not using Bootstrap Datepicker
        $('.js-datepicker').datepicker({
            format: 'yyyy-mm-dd'
        });
    });
</script>
{% endblock %}

{% block body %}
<div class="row">
    <div class="col-md-3 mb-5 ms-5 card filter">
            {% include "hotelrequest/_form_filter.html.twig" %}
    </div>
    <div class="col-md-3 mt-5 ms-5">
    </div>
    <div class="col-md-8">
            <div class="d-flex justify-content-end mb-2">
                {{knp_pagination_sortable(hotels,'Prix', 'prix')}}
            </div>
            {% for hotel in hotels %}
            {% include "admin/crud_voyage/hotel/_affichage_hotel.html.twig" %}
                            <li><a href="{{path('hotel_details',{id:hotel.id})}}" class="btn btn-primary">Voir details</a></li>
                        </ul>                            
                    </div>
            </div>
                    {% for c in hotel.vols %}
                <div class="admin_place_vol mb-3">
                    <div class="admin_place_vol_economique">
                        <p>nombre de place en classe économique : {{ c.classeEconomique }} {{ c.classeEconomique |badge }}</p>
                    </div>
                    <div class="admin_place_vol_affaire">
                        <p>nombre de place en classe affaire : {{ c.classeAffaire }} {{ c.classeAffaire |badge }}</p>
                    </div>
                </div>                            
                    {% endfor %}
            {% endfor %}
        </div>
    </div>
</div>
<div class="navigation">
{{ knp_pagination_render(hotels) }}
</div>

{% endblock %}

templates/hotelrequest/test.html.twig
{% extends "base.html.twig" %}
{% block javascripts %}
    {{ parent() }}
<script>
$(document).ready(function() {
    var minDate = new Date();
    $("#depart").datepicker({
        showAnim: 'drop',
        numberOfMonth: 1,
        minDate: minDate,
        dateFormat: 'dd/mm/yy',

    });
    $("#return").datepicker({
        showAnim: 'drop',
        numberOfMonth: 1,
        minDate: minDate,
        dateFormat: 'dd/mm/yy',
    });
});
let input = $('input').get(0); // conversion from jquery to regular element
</script>
{% endblock %}

{% block title %}hotels details{% endblock %}
{% block body %}
 <div id="booking" class="section">
        <div class="section-center">
            <div class="container">
                <div class="row">
                    <div class="booking-form">
                        <form metod="GET" action="{{path('hotelrequest')}}">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <span class="form-label">aeroport de départ</span>
                                        <input name="" class="form-control" type="text" placeholder="City or airport">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <span class="form-label">Destination Ville</span>
                                        <input name="q" class="form-control" type="text" placeholder="City">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <span class="form-label">Departing</span>
                                        <input name="depart" class="form-control" type="date" id="depart" placeholder="Depart Date">
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <span class="form-label">Returning</span>
                                        <input name="retour" class="form-control" type="date" id="return" placeholder="Return Date">
                                    </div>
                                </div>
                                {# <div class="col-md-2">
                                   <div class="form-group">
                                        <span class="form-label">Adult</span>
                                        <input name="Adult" class="form-control" type="number" min="0" step="1">
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <span class="form-label">Children -18</span>
                                        <input name="Children -18" class="form-control" type="number" min="0" step="1">
                                    </div>
                                </div>
                            </div> #}
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                         <input class="form-check-input" name="economie" type="checkbox" value="1" id="flexCheckDefault">
                                        <label class="form-check-label" for="flexCheckDefault">
                                           Classe Economique 
                                        </label>
                                        </div>
                                        <div class="form-check">
                                        <input class="form-check-input" type="checkbox" value="1" id="flexCheckChecked" name="affaire">
                                        <label class="form-check-label" for="flexCheckChecked">
                                            Classe Affaire
                                        </label>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-btn">
                                        <button type="submit" class="submit-btn">valider</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </form>
{% endblock %}